name: sewer-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=1.3.0
  - numpy>=1.20.0
  - plotly>=5.0.0
  - dash>=2.0.0
  - holidays>=0.20
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - nbformat>=4.2.0
  - pip
  - pip:
    - pymoo>=0.6.0